motor_0:
  name_joint: left_joint
  bridge: {PWM_dead_zone: 0.0, PWM_frequency: 1, h_bridge_enable: 0,
      Current_Offset: 0.8425, Current_Gain: 0.0623, 
      volt_gain: 0.0, volt_offset: 12.0}
  diagnostic:
    current: {critical: 2.0, warning: 1.0}
    temperature: {critical: 50.0, warning: 30.0}
  emergency: {Bridge_off: 2.0, Slope_time: 1.0, Timeout: 500}
  encoder: {CPR: 300, channels: 2, position: 1, z_index: 0}
  pid:
    current: {Enable: false, Frequency: 1, Kp: 0.0, Ki: 0.0, Kd: 0.0}
    velocity: {Enable: true, Frequency: 1000, Kp: 10.0, Ki: 5.0, Kd: 0.0}
  ratio: 30.0
  rotation: 1
motor_1:
  name_joint: right_joint
  bridge: {PWM_dead_zone: 0.0, PWM_frequency: 1, h_bridge_enable: 0,
      Current_Offset: 0.8425, Current_Gain: 0.0623, 
      volt_gain: 0.0, volt_offset: 12.0}
  diagnostic:
    current: {critical: 2.0, warning: 1.0}
    temperature: {critical: 50.0, warning: 30.0}
  emergency: {Bridge_off: 2.0, Slope_time: 1.0, Timeout: 500}
  encoder: {CPR: 300, channels: 2, position: 1, z_index: 0}
  pid:
    current: {Enable: false, Frequency: 1, Kp: 0.0, Ki: 0.0, Kd: 0.0}
    velocity: {Enable: true, Frequency: 1000, Kp: 10.0, Ki: 5.0, Kd: 0.0}
  ratio: 30.0
  rotation: -1
